version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: emailtriage
      POSTGRES_PASSWORD: emailtriage
      POSTGRES_DB: emailtriage
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
